#!/bin/bash

# Legacy SSH Enabler build script
version="v1.0"
program="lsshe"
release_name="legacy-ssh-enabler-$version"
release_files="$program *.md images"

cd "$(dirname "$0")"

version=v$version
rm -rf "$release_name" "$release_name".zip "$release_name".deb *.rpm

if [ "$1" == "clean" ]; then
    exit 0
fi

mkdir -p "$release_name"/usr/bin
mkdir -p "$release_name"/DEBIAN
cp control "$release_name"/DEBIAN
cp $program "$release_name"/usr/bin
dpkg-deb --build "$release_name"

rm -rf "$release_name"

mkdir "$release_name"
cp -r ${release_files} "$release_name"

chmod -R 777 "$release_name"
zip -r "$release_name".zip "$release_name"

rm -rf rpm-tmp
mkdir -p rpm-tmp/RPMS rpm-tmp/SPECS rpm-tmp/SOURCES rpm-tmp/BUILD
cp $program.spec rpm-tmp/SPECS
cp $program rpm-tmp/SOURCES
rpmbuild -bb --target noarch rpm-tmp/SPECS/$program.spec --define "_topdir $PWD/rpm-tmp"
mv rpm-tmp/RPMS/noarch/*.rpm .
rm -rf rpm-tmp
