#!/bin/bash

# Legacy SSH Enabler build script
version="1.0.1"
program="lsshe"
release_name="legacy-ssh-enabler-v$version"
release_files="$program *.md images"

cd "$(dirname "$0")"

rm -rf "$release_name" *.zip *.deb *.rpm

if [ "$1" == "clean" ]; then
    exit 0
fi

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed"
    sed_args="-i"
else
    echo "Info: using BSD sed"
    sed_args="-i '' -E"
fi

sed "$sed_args" "s|^VERSION=.*|VERSION=$version|" control
sed "$sed_args" "s|Version:.*|Version: $version|" $program.spec

mkdir -p "$release_name"/usr/bin
mkdir -p "$release_name"/DEBIAN
cp control "$release_name"/DEBIAN
cp $program "$release_name"/usr/bin
dpkg-deb --build "$release_name"

rm -rf "$release_name"

mkdir "$release_name"
cp -r ${release_files} "$release_name"

chmod -R 777 "$release_name"
zip -r "$release_name".zip "$release_name"

rm -rf rpm-tmp
mkdir -p rpm-tmp/RPMS rpm-tmp/SPECS rpm-tmp/SOURCES rpm-tmp/BUILD
cp $program.spec rpm-tmp/SPECS
cp $program rpm-tmp/SOURCES
rpmbuild -bb --target noarch rpm-tmp/SPECS/$program.spec --define "_topdir $PWD/rpm-tmp"
mv rpm-tmp/RPMS/noarch/*.rpm .
rm -rf rpm-tmp
